spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-ms
          uri: lb://USERS-MS
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: movies-api
          uri: lb://MOVIES-API
          predicates:
            - Path=/api/movies/**
          filters:
            - StripPrefix=2
        - id: ms-bills
          uri: lb://MS-BILLS
          predicates:
            - Path=/api/bills/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true